### ISSUE TITLE
Support for false start /early data in TLS 1.2

### ISSUE THREAD

**Issue by kiranns** [eduardsui/tlse#38]

**Comment by kiranns** [comment]
I am planning to use TLSe with kTLS in an enterprise setting. I would need support for false-start (sending app data after 1-RTT) with TLS 1.2. I would be grateful if you can implement that. Support for TCP fast open would be a plus.

**Comment by eduardsui** [comment]
Hello,

TCP fast open is TCP-transport-layer-related. You should just setsockopt TCP_FASTOPEN to your socket layer and you're good to go. Why don't you simply use TLS 1.3 instead of TLS 1.2 false-start? For TLS 1.2 it is fairly simple to implement, it will try to add it these days. However, it will be off by default.

**Comment by eduardsui** [comment]
Compile with `-DTLS_12_FALSE_START`.

**Comment by kiranns** [comment]
Thanks for the prompt response. I will try it out.

1. TCP FAST OPEN is indeed a TCP level option. However, the benefits of
that has to be leveraged by the TLS layer. The 'Client Hello' has to be
sent to the other side along with the 'SYN'. This requires changes inside
tlse, I presume by using the sendmsg call with special flags. This would
cut down one 1-RTT. There have been some security concerns regarding using
this. If you havent already, please take a look at Adam Langley's blog on
this issue (if I recall correctly).

2. Another request: please enable the tls_write and tls_read calls to take
in iovec structures. This would help avoiding 1-copy (at least) into a flat
buffer while sending large amounts, something that we need for our
use-case. In addition, if you can avoid further copies of the data within
the TLS layer for processing (for example, during encryption), that would
be great.

3. Another new request: In the newer Linux kernels, we can do zero-copy
between user-space and kernel for socket data. Adding that functionality
would also help with avoiding one more copy in the path for large data.
Here are the references I am talking about:
On the Tx side: https://lwn.net/Articles/726353/
On the Rx side: https://lwn.net/Articles/752046/
These are also TLS level changes.

**Comment by eduardsui** [comment]
Hello,

TLSe is transport-layer agnostic. I try to keep a logical separation between socket I/O and TLS layer. The only exception is kTLS.

For example:
```
    while ((read_size = recv(sockfd, client_message, sizeof(client_message) , 0)) > 0) {
        tls_consume_stream(context, client_message, read_size, validate_certificate);
        ...
    }
```
And:
```
    unsigned int out_buffer_len = 0;
    const unsigned char *out_buffer = tls_get_write_buffer(context, &out_buffer_len);
    ...
    int res = send(client_sock, (char *)out_buffer, out_buffer_len, 0);
    ...
    tls_buffer_clear(context);
}
```
This code should be in your client application (not inside TLSe). You're free to use any flags you would like.

For TCP fast open+ TLS you should do something like this:
```
tls_sni_set(context, "hostname");
tls_client_connect(context)

connect(sockfd, ...)
// do your TCP-related stuff here
tls_get_write_buffer(context, ...);

send(...) or sendmsg(...) or anything you would like until write buffer is empty
```
Also, you may add a function like this:
```
const unsigned char *tls_reown_write_buffer(struct TLSContext *context, unsigned int *outlen) {
..
    *outlen = context->tls_buffer_len;
    const unsigned char *buffer = context->tls_buffer;
    context->tls_buffer = NULL;
    context->tls_buffer_len = 0;
    return buffer;
}
```
This should answer point 1 and 3. For point 2, I'm not sure if there is a real benefit, because ``tls_write`` takes a buffer that will be packed into a TLS record. The buffer is not copied nor stored, I'm not sure about the benefits here. Same goes for ``tls_get_write_buffer`` which provides access to internal buffer (no copy). I think that maybe it would be trivial to store a list of iovec structures instead of TLSe write buffer, but this will not be backwards compatible. But I also think you would be better using TLSe + kTLS + splice/sendfile instead.

Also, I don't recommend using the synchronous SSL_* compatible APIs. Those perform indeed some socket I/O, but only at a basic level.

Note that this is an open-source product (public-domain). Feel free to contribute with anything you consider useful by cloning and PR.
