### ISSUE TITLE
tlssimpleserver.c: SSL received an unexpected Server Key Exchange handshake message..

### ISSUE THREAD

**Issue by mladinox** [eduardsui/tlse#4]
When testing the supplied example "tlssimpleserver.c", the browser throws the error:
Error code: ssl_error_rx_unexpected_server_key_exch

I'm using cert.pem and key.pem created with openssl

Thank you..

**Comment by eduardsui** [comment]
Can You attach cert.pem and key.pem for debugging? If yes, I will fix it
today.

**Comment by eduardsui** [comment]
Ok, managed to reproduce the problem. Is linked to RSA certificates generated with openssl (fixed already ECC certificates for prime256v1).

**Comment by eduardsui** [comment]
Ok, found the problem:

You must generate the certificate as:

`openssl req -nodes -new -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj "/CN=localhost"`

It should work now. Can you confirm that it works ?

**Comment by mladinox** [comment]
Yes..!  It works..!
Whats wrong?

**Comment by eduardsui** [comment]
You were using X.509 v1 certificates (instead of v3). I've added basic, limited support for v1 to TLSe (modified tlse.c and tlse.h). Clone and it should work. I do not recommend using v1 certificates.

You may use openssl to check your certificate: `openssl x509 -in cert.pem -text -noout`

Alternatively you may compile with -DDEBUG flag.
